"""Compatibility facade for checkpoint closeout pipeline helpers."""

from __future__ import annotations

from .context import (
    _closeout_candidate_clusters,
    _collect_candidate_lineage_hints,
    _collect_receipt_paths,
    _derive_closeout_skill_plan,
    _load_context_checkpoint_note,
    _load_context_checkpoint_notes,
    _load_context_surface_handoff,
    _load_receipt_payloads,
    _load_reviewed_surface_handoff,
    _resolve_closeout_session_ref,
    _surface_handoff_path,
    _validate_repo_root_closeout_scope,
)
from .contracts import (
    CHECKPOINT_CLOSEOUT_AUTHORITY_CONTRACT,
    DonorHarvestOutputs,
    ProgressionLiftOutputs,
    QuestHarvestOutputs,
)
from .evidence import (
    _extract_codex_trace_entry,
    _flatten_codex_content_text,
    _merge_closeout_evidence,
    _read_reviewed_artifact,
    _read_session_trace,
)
from .execution import (
    _axis_delta_for_movement,
    _build_core_skill_receipt,
    _build_donor_harvest_outputs,
    _build_progression_lift_outputs,
    _build_quest_harvest_outputs,
    _progression_cautions,
    _progression_signals_from_reviewed_artifact,
    _progression_verdict,
    _quest_triage_notes,
)
from .followthrough import (
    _approval_posture_for_next_skill,
    _build_closeout_followthrough_decision,
    _build_owner_followthrough_map,
    _closeout_followthrough_alternatives,
    _cluster_text,
    _has_blocked_signal,
    _has_upgrade_pressure,
    _is_repair_cluster,
    _is_route_cluster,
    _primary_lineage_cluster,
    _requested_followthrough_decision_class,
)
from .owner_handoff import (
    _build_accepted_candidate,
    _checkpoint_closeout_handoff_root,
    _checkpoint_owner_follow_through_key,
    _has_reviewed_closeout_owner_handoff_for_repo,
    _load_checkpoint_quest_unit_name,
    _load_closeout_owner_handoff_for_session,
    _nearest_wrong_target,
    _owner_reason,
    _quest_promotion_fields,
    _write_checkpoint_owner_handoff,
)

__all__ = [
    "CHECKPOINT_CLOSEOUT_AUTHORITY_CONTRACT",
    "DonorHarvestOutputs",
    "ProgressionLiftOutputs",
    "QuestHarvestOutputs",
    "_approval_posture_for_next_skill",
    "_axis_delta_for_movement",
    "_build_accepted_candidate",
    "_build_closeout_followthrough_decision",
    "_build_core_skill_receipt",
    "_build_donor_harvest_outputs",
    "_build_owner_followthrough_map",
    "_build_progression_lift_outputs",
    "_build_quest_harvest_outputs",
    "_checkpoint_closeout_handoff_root",
    "_checkpoint_owner_follow_through_key",
    "_closeout_candidate_clusters",
    "_closeout_followthrough_alternatives",
    "_cluster_text",
    "_collect_candidate_lineage_hints",
    "_collect_receipt_paths",
    "_derive_closeout_skill_plan",
    "_extract_codex_trace_entry",
    "_flatten_codex_content_text",
    "_has_blocked_signal",
    "_has_reviewed_closeout_owner_handoff_for_repo",
    "_has_upgrade_pressure",
    "_is_repair_cluster",
    "_is_route_cluster",
    "_load_checkpoint_quest_unit_name",
    "_load_closeout_owner_handoff_for_session",
    "_load_context_checkpoint_note",
    "_load_context_checkpoint_notes",
    "_load_context_surface_handoff",
    "_load_receipt_payloads",
    "_load_reviewed_surface_handoff",
    "_merge_closeout_evidence",
    "_nearest_wrong_target",
    "_owner_reason",
    "_primary_lineage_cluster",
    "_progression_cautions",
    "_progression_signals_from_reviewed_artifact",
    "_progression_verdict",
    "_quest_promotion_fields",
    "_quest_triage_notes",
    "_read_reviewed_artifact",
    "_read_session_trace",
    "_requested_followthrough_decision_class",
    "_resolve_closeout_session_ref",
    "_surface_handoff_path",
    "_validate_repo_root_closeout_scope",
    "_write_checkpoint_owner_handoff",
]
